### ISSUE TITLE
upgrade to QtWebEngine 5.15.7

### ISSUE THREAD

**Issue by waddlesplash** [korli/qtwebengine-haiku#2]
As in title. This version seems to be based on Chromium 87, with security patches to 96, I think.

I may have time to look into this if nobody else intends to.

**Comment by waddlesplash** [comment]
@korli, unless you intend to / are still working on things here, would you be opposed to granting me push access to this repo, so I can work on such things?

**Comment by waddlesplash** [comment]
Ah, I see you already started a branch for it. Very good then :)

**Comment by waddlesplash** [comment]
@korli, master still seems to be on the old version; did you make a change there or did you import the new source directly?

**Comment by korli** [comment]
master is now on the new version

**Comment by korli** [comment]
done in haiku-5.15.7
