### ISSUE TITLE
Media support?

### ISSUE THREAD

**Issue by waddlesplash** [korli/qtwebengine-haiku#3]
@threedeyes mentioned in https://github.com/haikuports/haikuports/commit/810e5832b3aaf5a834834584c1298fc24dd5bc40 that:

>  When I was building qtwebengine 5.12.3 - I had html5 video working fine, but no sound. For sound we need to write an output module, apparently.

The current version has no media support (@korli, not quite sure where that is done -- it does appear to be built with it?) so there are multiple things to work on here.

**Comment by threedeyes** [comment]
Haiku audio backend works fine:

![screenshot114](https://user-images.githubusercontent.com/2559260/142728381-9354ce6b-429b-46bf-97cc-145a8cf4ac35.png)
